### ISSUE TITLE
Duplicate Package?

### ISSUE THREAD

**Issue by seifsay3d-zz** [ConsoleTVs/vswr#2]
Hi there, I've used this package before https://github.com/Kong/swrv, however, I'm not sure what are the differences between both.

**Comment by ConsoleTVs** [comment]
There's an answer on the FAQ of this package about it. This package does support a few more options than the one you listed. Nevertheless, they are totally different implementations from the group up.

Their version was a port of the official vercel's SWR for react with vue-specific changes (as far as I know).

This one has been completely designed from the ground up to work only on vue 3+. and does support more options and features as for today. They both achieve the same goal.
