### ISSUE TITLE
version 1.0.0 don't work

### ISSUE THREAD

**Issue by dcyou** [ConsoleTVs/vswr#7]
by using the version 1.0.0 

![image](https://user-images.githubusercontent.com/6975084/101508117-9514ec80-3977-11eb-92a8-31a38803f0aa.png)
![image](https://user-images.githubusercontent.com/6975084/101508140-9a723700-3977-11eb-81ad-ebba4227db29.png)

don't know yet exactly what is the problem but for sure this is by using that version

**Comment by ConsoleTVs** [comment]
Can you provide an example code to reproduce the error?

**Comment by ConsoleTVs** [comment]
Is there any update on this? I will make more testing this week / weekend but it would be good if you could provide some feedback.

**Comment by dcyou** [comment]
I reverted my change and still use the 0.3.0 can't have more time on it. I spend some time on it yesterday without any good idea what append exactly

**Comment by dcyou** [comment]
I am using 0.4.0 version (not tagged on github)

**Comment by dcyou** [comment]
FYI bug found. You are using vue 3.0.4 and sound like between 3.0.2 and 3.0.4 something change and create a component circular registration. I can't find for now something who talk about it.
If I am not clear, this example create a circular registration:
![image](https://user-images.githubusercontent.com/6975084/105044224-c993c200-5a66-11eb-9d97-707406eadb67.png)
