### ISSUE TITLE
Help to access useSWR return

### ISSUE THREAD

**Issue by carmolim** [ConsoleTVs/vswr#8]
Hello, I'm trying to use SWR but I'm having some problems accessing the data inside the return. 
I'm deconstructing the return: 

```const { data:movies } = useSWR('http://showtimes.everyday.in.th/api/v2/movie/')```

And I'm getting this result:

![Screen Shot 2021-07-18 at 19 49 21 1](https://user-images.githubusercontent.com/2863161/126084492-d6a259c2-9cb4-4e22-9e8d-1ae3b9d4e40d.png)

And I need to access the array that I highlighted, but I don't know how to access it... 

I tried to deconstruct in other way also: 

```const { data: { data:movies } } = useSWR('http://showtimes.everyday.in.th/api/v2/movie/')```

But that didn't help either.

What I'm missing?

Thanks

**Comment by ConsoleTVs** [comment]
data is a reference (https://v3.vuejs.org/api/refs-api.html). You need to access the `.value` of the data. eg.

```js
const { data: movies } = useSWR('http://showtimes.everyday.in.th/api/v2/movie/')

watch(movies, () => console.log(movies.value.results))
```

References are automatically consumed on the `<template>` section, so you don't need to use `.value` there.

```vue
<template>
  <div>{{ JSON.stringify(movies.results) }}</div>
</template>
```
